apiVersion: v1
kind: Pod
metadata:
  name: hello-apfn
  labels:
    app: hello-apfn

spec:
  containers:
  - image: iacacrapfn.azurecr.io/deepthi2305/nodejs-demo:scanned
    imagePullPolicy: Always
    name: ms1-helloapfn
    ports:
    - containerPort: 8282
      protocol: TCP
          ---
apiVersion: v1
kind: Service
metadata:
  name: hello-apfn
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: hello-apfn-pls   
    
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 8282
  selector:
    app: hello-apfn
---